language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo clean
  - cargo build
  - cargo package
  - cargo test
  - cargo doc

# Added comment - 
